### ISSUE TITLE
[S1-PBI4] Membuat fitur home/landing page

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#10]
**User Story**
Sebagai Pengguna baru, saya ingin mengetahui fitur apa saja yang tersedia disuatu website, sehingga saya melakukan eksplore pada landing page dan melihat fitur apa saja yang bisa digunakan.

Size : 7 hari

**Activity Diagram Landing Page**
![Image](https://user-images.githubusercontent.com/88228674/229506491-93da7027-37fa-474c-ad3e-f273a16d2b4b.png)

**Halaman Tampilan Landing Page**

![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/a4e44113-bcb0-434b-888e-d6f78b2a6895)
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/1d907e27-65fd-40eb-8858-806b9dcaa4ca)
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/dff7dc42-cf72-4137-8f85-a7537c8f830f)
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/fc269e4a-c584-44fe-ba82-f1d47a13ee3f)
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/bc8b3461-6b9f-4f15-b1da-c91ca96dec11)

**Comment by ysb777** [comment]
![Image](https://user-images.githubusercontent.com/82760257/232288429-80c896bf-490a-4acb-8fe2-7e97a8f7a23d.png)
