### ISSUE TITLE
[S1-PBI5] Membuat fitur artikel budaya

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#11]
**User Story**
Sebagai pengguna, saya ingin mempelajari tentang budaya yang ada di website ini, sehingga saya mengakses halaman Artikel dari berbagai kebudayaan

Size : 7 hari

**Activity Diagram Artikel Budaya**
![Image](https://user-images.githubusercontent.com/88228674/229507806-21042757-7f3b-49b6-a426-4db4b44ba9d6.png)

**SS CRUD**
![Image](https://user-images.githubusercontent.com/80891747/232290319-e4308ac3-bbb0-49b5-b519-00765d173f4b.png)

**Tampilan Halaman Artikel Budaya**
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/de4f306b-2a3d-4f85-82e4-51d76c9a1b3b)

**Comment by ysb777** [comment]
![Image](https://user-images.githubusercontent.com/82760257/232283742-756f2519-fb63-4d93-9191-f4d3e4b43fde.png)
![Image](https://user-images.githubusercontent.com/82760257/232283741-cf23bced-7844-44c3-8079-e6b69e3bec2a.png)

**Comment by vadelaristi** [comment]
.
