### ISSUE TITLE
[S1-PBI6] Membuat fitur Navbar dan Footer

### ISSUE THREAD

**Issue by deamyn** [SI-RPL-2023/SI4402_D_YukBudayaKu#13]
**User Story**
Sebagai pengguna saya ingin mengakses fitur-fitur yang ada di website YuBu dengan cara cepat melalui navbar dan footer

Size : 5 Hari

**Activity Diagram Navbar**
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/88228674/bcf95434-2af3-4daf-ac3e-de1bbc915d6d)

**Activity Diagram Footer**
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/88228674/61650099-4917-42ed-95b9-164cdff047ce)

**SS CRUD**

Tampilan Navbar

![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/c2fd479d-0be1-4c1a-9d4b-e50feb2a69f6)

Tampilan Footer 

![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/c1556452-d020-4a57-b047-f532dc9e6316)

**Comment by ysb777** [comment]
![Image](https://user-images.githubusercontent.com/82760257/232283757-130712a3-238a-47e3-a3ee-9793a4780be6.png)
![Image](https://user-images.githubusercontent.com/82760257/232283758-f1deea30-77f2-494a-be43-59635948aeac.png)

**Comment by vadelaristi** [comment]
.
