### ISSUE TITLE
[S2-PBI7] Membuat fitur materi teks

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#31]
**User Story**
Sebagai budayawan saya ingin menambahkan materi teks 

Size : 5 Hari

**Activity Diagram Menambahkan Materi Teks**
![Image](https://user-images.githubusercontent.com/88228674/237519080-4f5513b5-3b31-47d1-80f1-662a6caffc34.png)

**SS CRUD**

**Tampilan Halaman Menambahkan Materi Teks**

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/44a5fb23-5258-42fa-9769-d530e83a7ddf)
