### ISSUE TITLE
[S2-PBI8] Membuat fitur quiz course

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#32]
**User Story**
Sebagai budayawan saya ingin menambahkan quiz course

Size : 7 Hari

**Activity Diagram Menambahkan Quiz Course**
![Image](https://user-images.githubusercontent.com/88228674/237519631-0e6c98ec-efb3-4c18-bcfa-3eff68e7c9a5.png)

**SS CRUD**

**Tampilan Halaman Menambahkan Quiz Course**

**Comment by ysb777** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/82760257/c09faa11-3a87-4ea0-a590-aba7620b698a)

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/c57d2d0f-d7ff-420b-969c-b07fca5af8af)
