### ISSUE TITLE
[S2-PBI9] Membuat fitur mengelola jawaban quiz

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#33]
**User Story**
Sebagai budayawan saya ingin mengelola jawaban quiz

Size : 7 Hari

**Activity Diagram Mengelola Jawaban Quiz**
![Image](https://user-images.githubusercontent.com/88228674/237520280-ae57e9cc-a2ec-4c7a-b846-42f45ef3b783.png)

**SS CRUD**

**Tampilan Halaman Mengelola Jawaban Quiz**

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/de3714b0-973a-4e95-a1e5-cbc3cda77e6e)
