### ISSUE TITLE
[S2-PBI5] Membuat fitur menambahkan course

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#37]
**User Story**
Sebagai budayawan saya ingin menambahkan course 

Size : 5 Hari

**Activity Diagram Menambahkan Course**
![Image](https://user-images.githubusercontent.com/88228674/237518346-b0251d68-0306-4ae5-8c63-338752c60249.png)

**SS CRUD**

**Tampilan Halaman Menambahkan Course**

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/973909a8-c8b7-40c8-a0b5-921df4cbe103)

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/898f4615-977b-4895-b1ce-58e6975e4a9c)
