### ISSUE TITLE
[S3-PBI2] Membuat fitur mengelola data user

### ISSUE THREAD

**Issue by deamyn** [SI-RPL-2023/SI4402_D_YukBudayaKu#45]
User Story 
Sebagai seorang admin saya ingin dapat mengelola data user dengan efisien.

Size :  5 Hari

Activity Diagram :

![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/3b203ba0-72dc-4760-872b-062b6c1d3a9a)

**Comment by gumballs17** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/80891747/894048b6-bc75-4ccd-a279-cc0372966ef4)

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/dd296d5f-3102-4d0b-9c53-efff1b13349e)
