### ISSUE TITLE
[S3-PBI3] Membuat fitur mengelola data teacher

### ISSUE THREAD

**Issue by deamyn** [SI-RPL-2023/SI4402_D_YukBudayaKu#46]
User Story: 
Sebagai admin saya ingin mengelola data guru.

Size: 5 hari

Activity Diagram Setting Course:
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/87889703/ef11b3bc-f728-482f-8a9b-82bc3758d77f)

**Comment by vadelaristi** [comment]
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/115638050/b8823f29-20c9-46ec-8508-883669f71d7c)
