### ISSUE TITLE
[S1-PBI1] Membuat fitur registrasi

### ISSUE THREAD

**Issue by gumballs17** [SI-RPL-2023/SI4402_D_YukBudayaKu#5]
**User Story**
Sebagai Pengguna saya ingin melakukan registrasi untuk mendapatkan akun sehingga saya bisa mengakses website dengan mengisi data seperti nama lengkap, alamat email, dan kata sandi.

Size : 5 Hari

**Activity Diagram Registrasi**
![Image](https://user-images.githubusercontent.com/88228674/228725570-611943b0-d246-4873-8074-bcc791080dbc.png)

**SS CRUD**
![Image](https://user-images.githubusercontent.com/80891747/232289654-b6c89939-9a10-4a72-a6e4-9db99dc66e7e.png)

**Tampilan Halaman Register*
![Image](https://github.com/SI-RPL-2023/SI4402_D_YukBudayaKu/assets/80891747/ed451ad5-fb03-4775-b74b-20de3046bf36)

**Comment by gumballs17** [comment]
Tampilan Halaman Register

![Image](https://user-images.githubusercontent.com/80891747/232282580-09de4d10-8d01-4ee5-acaa-a61504203f01.png)

**Comment by vadelaristi** [comment]
.
